name: Compile CV

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 使用 Docker 化的 TeX Live（與 Overleaf 更接近）
      - name: Build with latex-action (XeLaTeX + latexmk)
        uses: xu-cheng/latex-action@v3
        with:
          root_file: cv.tex
          latexmk_use_xelatex: true
          args: -interaction=nonstopmode -file-line-error -halt-on-error -jobname=chesterchu_cv -outdir=build
          # 如需額外系統字型，可加：extra_system_packages: "fonts-noto-cjk fonts-noto-color-emoji"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: chesterchu_cv
          path: build/chesterchu_cv.pdf

      - name: Configure auth for push
        if: ${{ github.event_name == 'push' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}"

      - name: Commit PDF back to repo (optional)
        if: ${{ github.event_name == 'push' }}
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add build/chesterchu_cv.pdf || true
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update chesterchu_cv.pdf (auto-generated)"
            git push
          fi
