name: Compile CV

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install TeX Live and tools
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            latexmk \
            texlive-xetex \
            texlive-latex-extra \
            texlive-fonts-recommended \
            texlive-fonts-extra \
            texlive-lang-cjk \
            texlive-lang-chinese \
            fonts-noto-cjk \
            fonts-noto-color-emoji
      - name: Build PDF with latexmk (XeLaTeX)
        run: |
          set -e
          # Build using xelatex via latexmk to ensure fonts (as in cv.tex header)
          latexmk -pdf -xelatex -interaction=nonstopmode -file-line-error -halt-on-error -jobname=my_cv cv.tex

      - name: Rename output to chesterchu_cv.pdf
        run: |
          # latexmk typically produces cv.pdf; handle a couple of common names
          if [ -f my_cv.pdf ]; then mv my_cv.pdf chesterchu_cv.pdf; fi

      - name: Upload chesterchu_cv.pdf as artifact
        uses: actions/upload-artifact@v4
        with:
          name: chesterchu_cv
          path: chesterchu_cv.pdf

      - name: Commit generated PDF back to repo (optional)
        if: ${{ github.event_name == 'push' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # Stage the generated PDF (ignore failure if not present)
          git add chesterchu_cv.pdf || true
          # If there are staged changes, commit and push
          if git diff --staged --quiet; then
            echo "No changes to commit for chesterchu_cv.pdf"
          else
            git commit -m "chore: update chesterchu_cv.pdf (auto-generated)"
            git push
          fi
